EcoG-io/iso15118

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/secc/states/din_spec_states.py, iso15118/secc/states/iso15118_20_states.py, iso15118/secc/states/iso15118_2_states.py, iso15118/shared/messages/enums.py, tests/conftest.py, tests/dinspec/evcc/evcc_mock_messages.py, tests/dinspec/secc/secc_mock_messages.py, tests/evcc/states/test_messages.py, tests/secc/states/test_iso15118_2_states.py, tests/secc/states/test_messages.py, tests/tools.py
This PR replaces the true/false return value for `is_authorized` with Accepted/Rejected/Ongoing, since an AuthorizationReq can be retried to deal with the time limit imposed by ISO 15118-2.
This also adds some unit tests and replaces a repeatedly-used test value with a constant.
=> fix: authorization state enum

.gitignore, iso15118/shared/pki/create_certs.sh
Added an extra command-line option -k to help generate certificates with names as expected by Keysight to help with testing. The certificates generated could be directly pasted into the generated-pki/pki-ext folder in TTWorkbench environment.
=> feat: Update create_certs.sh to help testing with Keysight

iso15118/secc/states/iso15118_2_states.py
Summary of change.
FaultMessage field in CertificateInstallationRes can't be empty as this would cause EXI encoding to fail.
In CertificateInstallationRes, the FaultMessage field was getting its value from str(e) where is e is Exception. If this was empty, that would cause EXI encoding to fail. Minor refactor to make sure the field is never empty.
=> Empty string field causes EXI encoding error

iso15118/secc/states/secc_state.py, iso15118/shared/comm_session.py, iso15118/shared/exceptions.py, iso15118/shared/exi_codec.py, iso15118/shared/messages/din_spec/body.py, iso15118/shared/messages/iso15118_2/body.py, iso15118/shared/messages/iso15118_2/msgdef.py, iso15118/shared/messages/iso15118_20/ac.py, iso15118/shared/messages/iso15118_20/common_types.py, tests/secc/messages/15118_2_invalid_messages.py
Fixed [AB#2522](https://dev.azure.com/switch-ev/09ab882d-ca4b-4b5b-b5b8-80603c12e5b2/_workitems/edit/2522)
For the ChargeParameterDiscoveryReq, it is supposed to be return FAILED_WRONG_CHARGE_PARAMETER when a wrong parameter received.
=> fix: wrong message parameters will return FAILED_WRONG_CHARGE_PARAMETER

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/secc/states/iso15118_2_states.py, iso15118/shared/messages/enums.py, pyproject.toml, tests/secc/states/test_iso15118_2_states.py, tests/shared/messages/test_app_protocol.py, tests/shared/messages/test_din_spec.py, tests/shared/messages/test_iso15118_2.py
improvement on [AB#2162](https://dev.azure.com/switch-ev/09ab882d-ca4b-4b5b-b5b8-80603c12e5b2/_workitems/edit/2162)
=> Improvement: Add get_cp_state method to iso15118 interface controller and include cp_status handler

iso15118/evcc/comm_session_handler.py, iso15118/evcc/evcc_settings.py, iso15118/evcc/states/sap_states.py, iso15118/secc/comm_session_handler.py, iso15118/secc/secc_settings.py, iso15118/secc/states/sap_states.py, iso15118/shared/exi_codec.py, iso15118/shared/messages/din_spec/datatypes.py, iso15118/shared/settings.py, iso15118/shared/states.py
This PR modifies Log levels:
- INFO level for TCP/TLS messages
- DEGUG level for 'waiting for up to ... sec' message
- INFO level for "chosen protocol" message
- INFO level for details on Request/Response messages
It also adds logs for project settings (env. variables) at start-up. It includes shared and EVCC/SECC-specific settings.
=> Feat/improve logging/ab#2898

iso15118/shared/pki/configs/moSubCA1Cert.cnf, iso15118/shared/pki/configs/moSubCA2Cert.cnf, iso15118/shared/pki/create_certs.sh
Updated create_certs.sh to generate certificates for some Keysight setup in .jks format.
Three files are generated:
- truststore.jks
- keystore.jks
- password.txt
=> Fix: create_certs to generate jks certs for Keysight

iso15118/secc/states/iso15118_2_states.py, tests/secc/states/test_iso15118_2_states.py, tests/secc/states/test_messages.py
ac evse status was static during the charging loop, so I modified the code to make it dynamic
=> get from the evse controller the ac evse status

iso15118/shared/security.py
Symptom:
Using the certificates generated using ./create_certs.sh, 'make run-secc' with TLS and PNC enabled, would fail in the CertificateInstallationReq handling:
`ERROR    2022-10-21 14:37:20,294 - iso15118.shared.security (977): CertNotYetValidError: Signature verification failed while checking certificate chain`
Issue:
The cryptography Certificate object represents the validity period of the certificate in UTC.  https://cryptography.io/en/latest/x509/reference/#cryptography.x509.Certificate
However, security.py is comparing cert.not_valid_before to the local time, and as a result,  the certificate is reported invalid for those of us in zones earlier than GMT.
Fix:
Use datetime.utcnow() instead of datetime.now() to get the current time
=> fix: use utcnow() to check certificate validity

iso15118/secc/comm_session_handler.py, iso15118/secc/states/iso15118_2_states.py, tests/secc/states/test_iso15118_2_states.py, tests/secc/states/test_messages.py
fix [AB#2850](https://dev.azure.com/switch-ev/09ab882d-ca4b-4b5b-b5b8-80603c12e5b2/_workitems/edit/2850)
According to spec 15118-2  [V2G2-475], the GenChallenge in AuthorizationReq should be the same in PaymentDetailsRes. Otherwise, we need to return FAILED_ChallengeInvalid.
[V2G2-475] The message 'AuthorizationRes' shall contain the ResponseCode
'FAILED_ChallengeInvalid' if the challenge response contained in the
AuthorizationReq message in attribute GenChallenge is not valid versus
the provided GenChallenge in PaymentDetailsRes.
=> genchallange check has been added for Authorization

iso15118/secc/__init__.py, iso15118/secc/comm_session_handler.py, iso15118/secc/main.py, iso15118/secc/transport/udp_server.py
- UDP socket now binds to the specific interface as defined in .env
- The interface to be used could be passed via start_secc_handler(). This helps remove reliance on env file when required.
=> Update udp socket to bind to specific interface

iso15118/secc/states/iso15118_2_states.py, tests/secc/states/test_iso15118_2_states.py, tests/secc/states/test_messages.py
fix [AB#2853](https://dev.azure.com/switch-ev/09ab882d-ca4b-4b5b-b5b8-80603c12e5b2/_workitems/edit/2853) 
[V2G2-225] The SECC shall send the negative ResponseCode
FAILED_ChargingProfileInvalid in the PowerDelivery response message if the EVCC sends a ChargingProfile which
is not adhering to the PMax values of all PMaxScheduleEntry elements according
to the chosen SAScheduleTuple element in the last ChargeParameterDiscoveryRes
message sent by the SECC.
=> Fix tc secc ac vtb power delivery 010

iso15118/secc/transport/udp_server.py
Use SO_BINDTODEVICE on linux to bind udp server to the specified interface. No changes to behaviour on Mac.
=> Fix: UDP server bind issue after PR#161

iso15118/secc/states/iso15118_20_states.py, iso15118/secc/states/iso15118_2_states.py, tests/iso15118_20/secc/test_iso15118_20_states.py, tests/iso15118_20/secc/test_messages.py, tests/secc/states/test_iso15118_2_states.py, tests/secc/states/test_messages.py
fix [AB#2821](https://dev.azure.com/switch-ev/09ab882d-ca4b-4b5b-b5b8-80603c12e5b2/_workitems/edit/2821) 
checks if the requested services ids in ServiceDetailReq are ids that were offered by the SECC in ServiceDiscoveryRes. if not, FAILED_SERVICE_ID_INVALID is returned.
=> Fix:service detail res

iso15118/secc/transport/udp_server.py
Fixing a bug that prevented the port from being bound to the socket under Linux
Signed-off-by: Sebastian Lukas <sebastian.lukas@pionix.de>
=> Bugfix - Binding the port to the socket does not work (Linux)

.github/workflows/pull-request.yml, README.md, poetry.lock
Updated the link to the new blog page
EDIT: I had also to update and set another python version to setup that was not 3.10.0 as we were now getting this error during the code quality check:
```shell
Run actions/setup-python@v2
Version 3.[1](https://github.com/SwitchEV/iso15118/actions/runs/3637883251/jobs/6139456419#step:3:1)0.0 was not found in the local cache
Error: Version 3.10.0 with arch x[6](https://github.com/SwitchEV/iso15118/actions/runs/3637883251/jobs/6139456419#step:3:7)4 not found
The list of all available versions can be found here: https://raw.githubusercontent.com/actions/python-versions/main/versions-manifest.json
```
=> fix: changed the link to the switch blog page on ISO 15118-20

iso15118/shared/messages/iso15118_2/datatypes.py
Summary:
NumEPriceLevels is the distinct price levels used across all SalesTariff entries. 
The validation assumed that NumEPriceLevels would be equal to the count of SalesTariff entries. This would be true only if every SalesTariff entry has as different price level. As the same price level could apply to two different SalesTariff entry, this check could wrongly fail the validation. Have removed the check. This issue was reported [here](https://github.com/SwitchEV/iso15118/issues/114).
=> AB#3740: Removed check in SalesTariff validator

README.md, iso15118/secc/transport/udp_server.py
- While testing on VM, the following lines had to be added for UDP server to come up.
```
if not hasattr(socket, "SO_BINDTODEVICE"):
socket.SO_BINDTODEVICE = 25
```
- Added a comment in readme suggesting running the project on a VM if using Windows.
=> Fix for UDP server failing to start on Linux VM

iso15118/shared/messages/din_spec/datatypes.py
This is fix for the issue mentioned here: 
https://github.com/SwitchEV/iso15118/issues/89
Error seen:
```
pydantic.error_wrappers.ValidationError: 1 validation error for ProfileEntryDetails
ChargingProfileMaxPower
ensure this value is less than or equal to 255 (type=value_error.number.not_le; limit_value=255)
```
The range specified for ChargingProfileMaxPower seems to be incorrect. The field type is PMaxType which is xs:short. This PR updates the range to match that of p_max in PMaxScheduleEntry.
```
<xs:complexType name="ProfileEntryType">
<xs:sequence>
<xs:element name="ChargingProfileEntryStart" type="xs:unsignedInt"/>
<xs:element name="ChargingProfileEntryMaxPower" type="PMaxType"/>
</xs:sequence>
</xs:complexType>
<xs:simpleType name="PMaxType">
<xs:restriction base="xs:short"/> …
```
=> Update datatypes.py - fixed range for ChargingProfileEntryMaxPower

iso15118/evcc/states/sap_states.py
SessionSetupReq was being sent from EVCC with the wrong V2GTP type 0x8001 (ISOV20PayloadTypes.SAP). Updated evcc/../sap_states.py to set `next_payload_type` to be ISOV20PayloadTypes.MAINSTREAM
This went unnoticed till now because the schema to be used for decoding the exi was first decided based on the protocol set in comm_session. Plus the fallback for unmatched v2gtp type was ISOV20PayloadTypes.MAINSTREAM and this unintentionally patched the issue at the secc end.
https://github.com/SwitchEV/iso15118/blob/2b146b483996863e82fca111db33dabf39f293fc/iso15118/shared/comm_session.py#L141
https://github.com/SwitchEV/iso15118/blob/2b146b483996863e82fca111db33dabf39f293fc/iso15118/shared/comm_session.py#L142
=> Fix: SessionSetupReq in -20 had the wrong V2GTP type

iso15118/secc/comm_session_handler.py, iso15118/secc/transport/tcp_server.py, iso15118/secc/transport/udp_server.py, iso15118/shared/comm_session.py, iso15118/shared/messages/sdp.py
1. When iso15118 starts up only UDP server is started.
2. When an SDP request is received, depending on the security setting in the request, either a TCP or TLS server is started. If TLS is requested, but a TLS server can't be started (maybe seccLeaf/cpoCertChain are not available), a TCP server is started - the SDP response reflects the type of TCP server available.
3. Once the first message is received over TCP connection, UDP server if paused.
4. At the end of the session, TCP server is killed and UDP resumes listening for SDP requests.
One minor change [V2GCommunicationSession](https://github.com/SwitchEV/iso15118/blob/d3e38dfbcf1c4fab65476c684a44bf34c09519ab/iso15118/shared/comm_session.py#L279) - we were relying on `self.writer.get_extra_info('peername')` to get …
=> Start TCP server after an SDP request is received.

iso15118/evcc/comm_session_handler.py, iso15118/evcc/states/iso15118_20_states.py
In ISO15118-20:
- If "Ongoing" response is received from EVSE, response with an unaltered AuthorizationReq(excluding the timestamp)
TODO: tests to be added on  EV side.
=> Handle "Ongoing"  from EVSE during authorization.

iso15118/shared/comm_session.py
fix for the [AB#4503](https://dev.azure.com/switch-ev/09ab882d-ca4b-4b5b-b5b8-80603c12e5b2/_workitems/edit/4503) 
* ConnectionResetError exception has been added for the receive.
=> ConnectionResetError has been added for receive

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/secc/states/iso15118_20_states.py, iso15118/secc/states/iso15118_2_states.py, tests/secc/states/test_iso15118_2_states.py
* in the Authorization state, evse status will be checked if it is able to deliver energy.
* if it is not ready, AuthohorizationRes will return ONGOING
=> is_ready_to_charge control added for Authorization

iso15118/shared/exificient_exi_codec.py
I ran into a situation running the iso15118 stack where the java background process spawned by JavaGateway was not getting terminated under certain conditions.  
The issue can be replicated as follows:
1. run evcc demo
2. kill the top level python process with -9
=> the java process remains
I ran into this issue while using a unit test framework and ended up with 100s of java processes running in the background which eventually used up all my RAM.
This patch fixes the issue for me both in the unit test framework and when force-killing the parent process.  The die_on_exit argument causes the [die-on-broken-pipe](https://github.com/py4j/py4j/blob/9e61991c7ac0c61066486204fe94936a1ff4e186/py4j-python/src/py4j/java_gateway.py#L303) flag to be passed to the [java …
=> terminate java gateway on exit

iso15118/secc/controller/simulator.py
Fixed dummy schedule generation to cope with departure_time greater than 172800 days.
=> AB#4965 : Fixed dummy schedule generation

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/secc/states/iso15118_2_states.py, tests/iso15118_2/secc/states/test_iso15118_2_states.py
If free service is set to true, then no SalesTariff is set in charging schedules.
=> AB#5093 Skip SalesTariff if free service.

iso15118/shared/messages/din_spec/body.py, tests/dinspec/evcc/evcc_mock_messages.py, tests/dinspec/evcc/test_dinspec_evcc_states.py
See section 9.4.1.2.3 Table 30 in DIN SPEC 70121
"If an SECC cannot provide such ID data, the value of the EVSEID is set to zero (00hex)."
=> EVSE ID min_length = 2
=> Fix min_length of EVSE ID for DIN protocol

README.md
Removed comment from readme stating dc is still under development.
=> Updated readme. Removed dc underdevelopment comment

iso15118/secc/states/iso15118_20_states.py, tests/iso15118_20/secc/test_iso15118_20_ac_states.py, tests/iso15118_20/secc/test_iso15118_20_dc_states.py, tests/iso15118_20/secc/test_messages.py
[V2G20 - 847] The EVCC shall signal CP State C or D no later than 250 ms after sending the first PowerDeliveryReq with ChargeProgress equals "Start" within V2G communication session.
=> JTT-52: Stop charging if state C not detected in PowerDelivery state.

iso15118/secc/states/iso15118_2_states.py
[V2G2-824] : The message 'PaymentDetailsRes' shall contain the ResponseCode 'FAILED_CertificateExpired' if the Contract Certificate contained in the PaymentDetailsReq message in attribute ContractSignatureCertChain is not yet valid.
=> Return FAILED_CertificateExpired is certificate is not yet valid

iso15118/evcc/states/iso15118_20_states.py
Dear Authors:
I change class ScheduleExchange(StateEVCC)   
if self.comm_session.selected_energy_service in (
ServiceV20.AC_BPT,
ServiceV20.DC_BPT,
):
to
if self.comm_session.selected_energy_service.service in (
ServiceV20.AC_BPT,
ServiceV20.DC_BPT,
):
Otherwise, ChannelSelection.DISCHARGE or ChannelSelection.CHARGE cannot be determined.
Many thanks,
Mike
=> ScheduleExchange(StateEVCC_bug)

.coveragerc, iso15118/evcc/states/iso15118_20_states.py
Check if ev processing if finished before accessing ev_power_profile for populating bpt_channel information.
=> Add bpt channel info only if evpowerprofile is available

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/shared/comm_session.py
Report session stop reason. When [stop()](https://github.com/SwitchEV/iso15118/blob/e73c5903df92e419b8bc88a61e02626fa62721a9/iso15118/shared/comm_session.py#L376) is called, the reason is passed to evse_controller.
=> Report session stop reason

iso15118/secc/states/iso15118_2_states.py, iso15118/shared/security.py, tests/iso15118_2/secc/states/test_iso15118_2_states.py
Avoid failing if local chain validation fails in PaymentDetails. This will still be performed in the backend. Tests added.
=> jtt-550_ignore_incorrect_mo_root_on_disk

iso15118/shared/comm_session.py
Fix for issue where uncaught ConnectionResetError was resulting in UDP server not resuming.
=> Fix for connection reset error

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/secc/states/din_spec_states.py, iso15118/secc/states/iso15118_20_states.py, iso15118/secc/states/iso15118_2_states.py
Added is_precharge flag to send_charging_command. Required as we use the same method during charging loop and precharge.
=> Added optional is_precharge flag to send_charging_command

iso15118/evcc/controller/interface.py, iso15118/evcc/controller/simulator.py, iso15118/evcc/states/din_spec_states.py, iso15118/evcc/states/iso15118_20_states.py, iso15118/evcc/states/iso15118_2_states.py, tests/dinspec/evcc/evcc_mock_messages.py
Fixes #356 and #264 
- Added enable_charging to evcc controller interface. This gives the EVCC the opertunity to go to state C (or B)
- Fixed an issue where the wrong flag was checked when receiving current demand response for EVSE initiated shutdown (DIN only)
=> EVCC enable charging and fix for DIN EVSE initiated stop

iso15118/evcc/states/sap_states.py
according to {urn:iso:std:iso:15118:-20:CommonTypes}SessionID the length must be 8
=> Fix SessionID length in SessionSetupReq for ISO15118-20

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/secc/states/iso15118_20_states.py
Return ongoing in ScheduleExchangeReq if evse is not ready.
=> Jtt 770 return ongoing if cs is not ready

iso15118/secc/states/din_spec_states.py, iso15118/secc/states/iso15118_20_states.py, iso15118/secc/states/iso15118_2_states.py, tests/iso15118_20/secc/test_iso15118_20_dc_states.py
Moved contactor status check for dc to be after a cable check response has been received.
=> Moved contactor status check for dc to be after cable check

iso15118/secc/controller/interface.py
Just a small typo I found when planning the integration into a research project.
(force pushed to rebase change on top of current upstream master)
=> fix typo in SECC interface.py

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/secc/states/din_spec_states.py, iso15118/secc/states/iso15118_20_states.py, iso15118/secc/states/iso15118_2_states.py, tests/shared/messages/test_interface.py
Add support to share CPD params with CS.
=> Share cpd params with CS.

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/secc/states/din_spec_states.py, iso15118/secc/states/iso15118_20_states.py, iso15118/secc/states/iso15118_2_states.py, tests/shared/messages/test_interface.py
Share display params coming from EV with the CS. This doesn't apply to -2 AC though - as the request is empty.
=> Share display params with CS.

iso15118/secc/controller/interface.py, iso15118/secc/controller/simulator.py, iso15118/secc/states/din_spec_states.py, iso15118/secc/states/iso15118_20_states.py, iso15118/secc/states/iso15118_2_states.py, tests/dinspec/secc/test_dinspec_secc_states.py, tests/iso15118_2/secc/states/test_iso15118_2_states.py, tests/iso15118_2/secc/states/test_messages.py, tests/iso15118_20/secc/test_iso15118_20_dc_states.py
Relaxed contactor status check for DC in -20, -2 and DIN. Tests added.
=> Relaxed contactor status check for DC.

iso15118/secc/controller/interface.py
=> Fixed comment.
