README.md

Some cleanup of readme formatting, such as where lines weren't breaking as intended.

docs: fix formatting issues

---

iso15118/secc/states/iso15118_2_states.py

One mod:
HLC is set to True before closing the contactor.

feat: set hlc charging before closing contactor

---

CHANGELOG.md
poetry.lock
pyproject.toml

Bump the version to do a release

chore: bump version to 0.8.0

---

CHANGELOG.md
pyproject.toml

- Version number updated to 0.8.1
- Changelog updated
- Added Ibrahim to authors' list.

bumped version to 0.8.1

---

poetry.lock
pyproject.toml

I tested locally and got no issues

bumped crypto version to 38.0.1

---

template.Dockerfile

Small clean up of the template dockerfile to remove some unneeded steps

fix: cleanup template dockerfile

---

iso15118/secc/comm_session_handler.py
iso15118/shared/comm_session.py
iso15118/shared/states.py
tests/conftest.py
tests/dinspec/secc/test_dinspec_secc_states.py

Include evse_id in log messages to help with debugging.

Minor logging improvement.

---

poetry.lock
pyproject.toml

Moves all dev dependencies to the new poetry syntax dev group, and update mypy to 1.2.0

fix: sort dev dependencies and update mypy

---

iso15118/secc/states/din_spec_states.py

- Add missing optional fields evse_max_current_limit, evse_max_voltage_limit, evse_max_power_limit inside CurrentDemandRes DIN70121

Add missing optional fileds in CurrentDemandRes DIN70121

---

iso15118/secc/controller/interface.py
iso15118/secc/controller/simulator.py
iso15118/secc/states/din_spec_states.py
iso15118/secc/states/iso15118_20_states.py
iso15118/secc/states/iso15118_2_states.py
tests/iso15118_2/secc/states/test_iso15118_2_states.py
tests/iso15118_20/secc/test_iso15118_20_ac_states.py
tests/iso15118_20/secc/test_messages.py

Return certificate validation result if available.

AB#5144:support to return certificate validation status.

---

iso15118/secc/__init__.py
iso15118/secc/comm_session_handler.py
iso15118/secc/transport/tcp_server.py

Running of UDP server is optional. Default behaviour stays the same as before.

Make running of udp server optional

---

iso15118/evcc/controller/simulator.py
iso15118/evcc/states/iso15118_20_states.py

Simulate precharge for 5 cycles before returning finished.

Simulate precharge ongoing before finished

---

iso15118/evcc/controller/simulator.py
iso15118/evcc/states/iso15118_20_states.py

Updated ev simulator to simulate ongoing WeldingDetection before returning finished.

Simulate welding detection ongoing before finished

---

CHANGELOG.md
Makefile
iso15118/secc/controller/interface.py
iso15118/secc/transport/udp_server.py
iso15118/shared/comm_session.py
iso15118/shared/exificient_exi_codec.py
mypy.ini
poetry.lock
pyproject.toml

This PR:
- Updates outdated interfaces
- Updates mypy config and fixes issues

JTT-138 Feat: update iso15118 interfaces

---

iso15118/secc/states/iso15118_2_states.py

Added evse_max_current to ChargingStatusRes message.

JTT-193: Add evse_max_current to ChargingStatusRes in 15118-2

---

iso15118/shared/comm_session.py

Log namespace value during debug.

log namespace value

---

iso15118/evcc/controller/simulator.py
iso15118/secc/controller/simulator.py
iso15118/secc/states/iso15118_2_states.py
iso15118/shared/messages/datatypes.py
poetry.lock

* EVSE voltage and current are set to EV voltage and current in the precharge phase to make Keysight happy.

Precharge EVSE voltage-current

---

iso15118/secc/controller/simulator.py
iso15118/shared/messages/datatypes.py
iso15118/shared/messages/iso15118_20/common_types.py
tests/iso15118_20/secc/test_iso15118_20_dc_states.py

Minor change to share exponent value repr function between Physical Value and RationalNumber types.

Minor refactor exponent_value_conversion

---

iso15118/secc/comm_session_handler.py

Added option to close tcp reader on SECC side.

Add option to close tcp reader from SECC

---

iso15118/secc/controller/ev_data.py

The issue was overwriting the max_voltage to None when there was no EVMaximumVoltageLimit field in currentDemandReq.

fixed the issue when parameters are none in currentdemandReq

---

iso15118/shared/messages/iso15118_20/common_messages.py

Fixed incorrect alias and missing member in PriceRule and AbsolutePriceSchedule respectively.

Fixed pydantic issues.

---

iso15118/secc/controller/ev_data.py

ev_min_current updation was missed in ev_data.

Added missed param in ev data
